FROM python:3.7-slim-buster

WORKDIR /validator

RUN python -m pip install --upgrade pip
RUN pip install poetry

COPY . /validator
RUN rm /validator/poetry.lock

RUN poetry config virtualenvs.create false \
  && poetry install --extras "ge" --no-interaction --no-ansi

ENTRYPOINT pytest tests/ -vv
