FROM python:3.7-slim-buster
RUN pip install poetry
COPY pyproject.toml /
RUN poetry config virtualenvs.create false \
&& poetry install --no-interaction --no-ansi
COPY . /validator
WORKDIR /validator
ENTRYPOINT pytest /validator/tests -vv
